### ISSUE TITLE
Add approve/reject submit buttons to the posting details pages

### ISSUE THREAD

**Issue by malemburg** [python-jobs-board/pythondotorg#3]
(The details page is the one showing the comment entry fields.)

This is needed to simplify the workflow. The pages currently just allow to post comments. The approve and reject buttons are on the review page only.

The buttons should submit the entered comment and set the status of the entry accordingly (including sending the emails this triggers; see #1 and #2).

**Comment by wbachnik** [comment]
I did a little research regarding that and unfortunately, it's not an easy thing to do. We're using a generic commenting framework [django-comments-xtd](https://github.com/danirus/django-comments-xtd) and I couldn't find an easy way to override the default form so that extra buttons are displayed and handled.
I can still think of other solutions, though:
1. Implement our own commenting for job offers,
2. Attempt to hack around the existing framework and handle the comment form ourselves using the framework's validation and models.
3. Create the Approve/Reject buttons outside of the form and handle them by ourselves. Implement simple JavaScript hook alerting reviewer that her entered comment would be lost if it's not submitted before using our new buttons.
4. ???

I think that solution from 3. is the simplest, but at the cost of a bit worse UI. Solution from 2. is better in terms of UI, but requires much more effort and testing. I'm not even considering 1.

Thoughts?

**Comment by malemburg** [comment]
On 12.05.2014 22:50, Wiktor Bachnik wrote:

> I did a little research regarding that and unfortunately, it's not an easy thing to do. We're using a generic commenting framework [django-comments-xtd](https://github.com/danirus/django-comments-xtd) and I couldn't find an easy way to override the default form so that extra buttons are displayed. There are some solutions, though:
> 1. Implement our own commenting for job offers,
> 2. Attempt to hack around the existing framework and handle the comment form ourselves using the framework's validation and models.
> 3. Create the Approve/Reject buttons outside of the form and handle them by ourselves. Implement simple JavaScript hook alerting reviewer that her entered comment would be lost if it's not submitted before using our new buttons.
> 4. ???
> 
> I think that solution from 3. is the simplest, but at the cost of a bit worse UI. Solution from 2.is better in terms of UI, but requires much more effort and testing. I'm not even considering 1.
> 
> Thoughts?

Agreed. We need the functionality - it doesn't have to look nice.

## 

Marc-Andre Lemburg

**Comment by wbachnik** [comment]
It won't look terrible, it just won't be seamless :-)
Anyway, I should be able to implement that in the evening if everything goes well.

**Comment by wbachnik** [comment]
Please review PR #14. The change is very simple, I'm more concerned about the wording.
Note that this was branched from PR #13 so it also contains commits implementing canned responses (for easier merge, unless #13 is rejected).

**Comment by wbachnik** [comment]
Forgot to mention: currently Approve/Reject action from the details view goes back to the review queue. Let me know if it should redirect the user back to the details view for the posting under review.

**Comment by malemburg** [comment]
The redirect should be fine. We'll figure this out when actually starting to use the system.

Closing for now. Thanks, Wiktor.
